log:
  filename: /var/log/bigbluebutton/bbb-transcription-controller.log
  level: info
  stdout: true
  gladiaProxy: /var/log/bigbluebutton/gladia-proxy.log

redis:
  host: 0.0.0.0
  port: "6379"
  # password: foobared
  publishChannel: 'from-akka-apps-redis-channel'

includePartialResults: true

# If set to false connection to the transcription provider will be kept open from
# the call start to the call hangup. Otherwise it will be opened/closed whenever a
# user start/stops talking. Setting to true might yield lower quality results
disconnectOnSilence: false
# If disconnectOnSilence is true we'll wait this time in seconds
# before closing the connection. If this is too low we might have too much
# connections/disconnections and final results might be cut too short
closeConnectionAfterSeconds: 10

# in mhz
# Valid values are '16' and '8', but 8 seems to be
# too low to get accurate transcriptions
sampleRate: '16'

# Each transcription server has its own config section
# startMessage and endMessage are the messages sent whenever mod_audio_fork's
# connection starts/ends

# servers/server registers transcription server websocket URLs
# I've configured my servers using an nginx reverse proxy for each
# language, see the example below

vosk:
  startMessage: '{"config": { "sample_rate": "" } }'
  endMessage: '{"eof" : 1 }'
  servers:
    en-US: wss://HOST/voskEN
    es-ES: wss://HOST/voskES
    pt-BR: wss://HOST/voskPT
    fr-FR: wss://HOST/voskFR

# TODO: whispering is still not supported, need to get
# the start/end messages right

gladia:
  apiUrl: 'https://api.gladia.io/v2/live'
  key: ''
  bitDepth: 16
  modelType: "base"
  endpointing: 0.05
  maxBeforeEndpointing: 5
  # Message confidence ranges from 0 to 1, messages below minConfidence are discarded
  minConfidence: 0.1
  # DEPRECATED: Provide a custom vocabulary to the model to improve accuracy of transcribing context specific words, technical terms, names, etc.
  # If empty, this field is ignored. Please be aware of a character limit of 600.
  # We need to use the new v2 format
  hint: ''
  server: ws://localhost:8777
  # DEPRECATED: startMessage and endMessage are deprecated for gladia
  startMessage: '{}'
  endMessage: '{}'
  translation:
    enabled: false
    languages: ["pt", "de", "en", "fr"]
    minConfidence: 0.1
  # DEPRECATED: won't be needed in the future
  proxy:
    enabled: true
    address: "wss://api.gladia.io/audio/text/audio-transcription"
    minPartialDuration: 3

whispering:
  startMessage: '{"config": { "sample_rate": ""} }'
  endMessage: '{"eof" : 1 }'
  server:  wss://HOST/whispering

# Setup freeswitch credentials to make ESL work

freeswitch:
  ip: 0.0.0.0
  port: 8021
  password:
